return {
  {
    "nvim-treesitter/nvim-treesitter",
    dependencies = { "hiphish/rainbow-delimiters.nvim" },
    opts = {
      ensure_installed = {
        "astro",
        "cmake",
        "cpp",
        "css",
        "fish",
        "gitignore",
        "go",
        "graphql",
        "http",
        "java",
        "html",
        "typescript",
        "tsx",
        "php",
        "rust",
        "scss",
        "ruby",
        "lua",
        "sql",
        "svelte",
      },
    },
  },
}
